apiVersion: batch/v1
kind: CronJob
metadata:
  name: mateapp-cronjob
  namespace: mateapp
spec:
  schedule: "*/4 * * * *"
  startingDeadlineSeconds: 100
  concurrencyPolicy: Allow
  successfulJobsHistoryLimit: 10
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mateapp-cronjob
              image: curlimages/curl
              command:
                - /bin/sh
                - -c
                - curl http://todoapp-service.todoapp.svc.cluster.local/api/health
              resources:
                requests:
                  cpu: "100m"
                  memory: "100Mi"
                limits:
                  cpu: "100m"
                  memory: "100Mi"
          restartPolicy: OnFailure
